/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Pr2Controllers
{
    public class JointControllerState : Message
    {
        //public const string RosMessageName = "pr2_controllers_msgs/JointControllerState";
        public override string RosMessageName => "pr2_controllers_msgs/JointControllerState";

        public Header header { get; set; }
        public double set_point { get; set; }
        public double process_value { get; set; }
        public double process_value_dot { get; set; }
        public double error { get; set; }
        public double time_step { get; set; }
        public double command { get; set; }
        public double p { get; set; }
        public double i { get; set; }
        public double d { get; set; }
        public double i_clamp { get; set; }

        public JointControllerState()
        {
            this.header = new Header();
            this.set_point = 0.0;
            this.process_value = 0.0;
            this.process_value_dot = 0.0;
            this.error = 0.0;
            this.time_step = 0.0;
            this.command = 0.0;
            this.p = 0.0;
            this.i = 0.0;
            this.d = 0.0;
            this.i_clamp = 0.0;
        }

        public JointControllerState(Header header, double set_point, double process_value, double process_value_dot, double error, double time_step, double command, double p, double i, double d, double i_clamp)
        {
            this.header = header;
            this.set_point = set_point;
            this.process_value = process_value;
            this.process_value_dot = process_value_dot;
            this.error = error;
            this.time_step = time_step;
            this.command = command;
            this.p = p;
            this.i = i;
            this.d = d;
            this.i_clamp = i_clamp;
        }
    }
}
