/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Pr2Controllers
{
    public class Pr2GripperCommand : Message
    {
        //public const string RosMessageName = "pr2_controllers_msgs/Pr2GripperCommand";
        public override string RosMessageName => "pr2_controllers_msgs/Pr2GripperCommand";

        public double position { get; set; }
        public double max_effort { get; set; }

        public Pr2GripperCommand()
        {
            this.position = 0.0;
            this.max_effort = 0.0;
        }

        public Pr2GripperCommand(double position, double max_effort)
        {
            this.position = position;
            this.max_effort = max_effort;
        }
    }
}
