# Maximum joint-space acceleration, just for safety.
max_joint_acceleration: 3.0

# Maximum cartesian end-effector velocity
max_position_acceleration: 2.0
max_position_velocity: 0.5
max_rotation_velocity: 3.0

# Control frequency
arm_frequency: 30

# left arm velocity factor
feedback_velocity_factor: 0.1
feedforward_velocity_factor: 1

start_rotation_q:
   x: -0.957
   y: 0.234
   z: -0.166
   w: 0.0414
start_position:
   x: 0.492
   y: 0.475
   z: 0.941
start_joints: [1.320677555902451,0.728430591131164, 0.9522966916474169, -1.801631489637284, 1.202594159483151, -0.54644481189654, 1.0]

group_name: left_arm

eef_link: l_gripper_tool_frame

joint_names:
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_forearm_roll_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint

teleop_signal:
  start: 1
  stop: 3

arm_controller_name: l_arm_controller

goal_topic: /left/goal_transform_stamp
