# Maximum joint-space acceleration, just for safety.
max_joint_acceleration: 3.0

# Maximum cartesian end-effector velocity
max_position_acceleration: 2.0
max_position_velocity: 0.5
max_rotation_velocity: 3.0

# Control frequency
arm_frequency: 20

# right arm velocity factor
feedback_velocity_factor: 0.0
feedforward_velocity_factor: 1.0

start_rotation_q:
   x: 0.252
   y: 0.595
   z: 0.588
   w: 0.486
start_position:
   x: 0.534
   y: -0.444
   z: 0.923

start_joints: [-1.014539424783184, -0.16621685758595936, -1.4204770431417315, -1.4667866086015817, -0.1357455, 0.0, 0.0]


group_name: right_arm

eef_link: rh_palm

joint_names:
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - rh_WRJ2
    - rh_WRJ1

teleop_signal:
  start: 2
  stop: 4

arm_controller_name: r_arm_controller

goal_topic: /right/goal_transform_stamp

display_trajectory_name: right_display_goal_path
