# Maximum joint-space acceleration, just for safety.
max_joint_acceleration: 3.0

# Maximum cartesian end-effector velocity
max_position_acceleration: 2.0
max_position_velocity: 0.5
max_rotation_velocity: 3.0

# Control frequency
arm_frequency: 30

# left arm velocity factor
feedback_velocity_factor: 0.1
feedforward_velocity_factor: 1

start_rotation_q:
   x: 0.074 
   y: -0.08994921671655626
   z: -0.1739528986195165
   w: 0.9778568379567009
start_position:
   x: 0.7261074616971745
   y: 0.3666474616614457
   z: 0.8006709781933222
start_joints: [0.8980641269329809,0.3585279564255547, 1.1671460969943734, -1.4356624569934142, 2.1544924624335713, -0.1738373410917109, 3.1748988051406073]

group_name: left_arm

eef_link: l_gripper_tool_frame

joint_names:
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_forearm_roll_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint

teleop_signal:
  start: 1
  stop: 3

arm_controller_name: l_arm_controller

goal_topic: /left/goal_transform_stamp
