/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.ApriltagRos
{
    public class AprilTagDetectionArray : Message
    {
        //public const string RosMessageName = "apriltag_ros/AprilTagDetectionArray";
        public override string RosMessageName => "apriltag_ros/AprilTagDetectionArray";
        public Header header { get; set; }
        public AprilTagDetection[] detections { get; set; }

        public AprilTagDetectionArray()
        {
            this.header = new Header();
            this.detections = new AprilTagDetection[0];
        }

        public AprilTagDetectionArray(Header header, AprilTagDetection[] detections)
        {
            this.header = header;
            this.detections = detections;
        }
    }
}
