/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Pr2GripperSensor
{
    public class PR2GripperPressureData : Message
    {
        public const string RosMessageName = "pr2_gripper_sensor_msgs/PR2GripperPressureData";

        //  Note: This message is intended for internal package use only and is NOT a part of the public API. This data is not publicaly published in ROS.
        //  the pressure array for the left and right fingers
        public double[] pressure_left { get; set; }
        public double[] pressure_right { get; set; }
        public double rostime { get; set; }

        public PR2GripperPressureData()
        {
            this.pressure_left = new double[22];
            this.pressure_right = new double[22];
            this.rostime = 0.0;
        }

        public PR2GripperPressureData(double[] pressure_left, double[] pressure_right, double rostime)
        {
            this.pressure_left = pressure_left;
            this.pressure_right = pressure_right;
            this.rostime = rostime;
        }
    }
}
