/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Pr2GripperSensor
{
    public class PR2GripperGrabData : Message
    {
        public const string RosMessageName = "pr2_gripper_sensor_msgs/PR2GripperGrabData";

        //  the control state of our realtime controller
        public PR2GripperSensorRTState rtstate { get; set; }

        public PR2GripperGrabData()
        {
            this.rtstate = new PR2GripperSensorRTState();
        }

        public PR2GripperGrabData(PR2GripperSensorRTState rtstate)
        {
            this.rtstate = rtstate;
        }
    }
}
