/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Pr2GripperSensor
{
    public class PR2GripperForceServoCommand : Message
    {
        public const string RosMessageName = "pr2_gripper_sensor_msgs/PR2GripperForceServoCommand";

        //  the amount of fingertip force (in Newtons) to apply.
        //  NOTE: the joint will squeeze until each finger reaches this level
        //  values < 0 (opening force) are ignored
        // 
        //  10 N can crack an egg or crush a soda can.
        //  15 N can firmly pick up a can of soup.
        //  Experiment on your own.
        // 
        public double fingertip_force { get; set; }

        public PR2GripperForceServoCommand()
        {
            this.fingertip_force = 0.0;
        }

        public PR2GripperForceServoCommand(double fingertip_force)
        {
            this.fingertip_force = fingertip_force;
        }
    }
}
