/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Pr2GripperSensor
{
    public class PR2GripperSlipServoCommand : Message
    {
        public const string RosMessageName = "pr2_gripper_sensor_msgs/PR2GripperSlipServoCommand";

        //  this command is currently blank, but may see additional variable
        //  additions in the future
        //  see the param server documentation for a list of variables that effect
        //  slip servo performance

        public PR2GripperSlipServoCommand()
        {
        }
    }
}
