/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Pr2GripperSensor
{
    public class PR2GripperFindContactCommand : Message
    {
        public const string RosMessageName = "pr2_gripper_sensor_msgs/PR2GripperFindContactCommand";

        //  set true if you want to calibrate the fingertip sensors on the start
        //  of the find_contact action. While this is not necessary (and
        //  the default value will not calibrate the sensors) for best 
        //  performance it is recommended that you set this to true each time 
        //  you are calling find_contact and are confident the fingertips are 
        //  not touching anything
        //  NOTE: SHOULD ONLY BE TRUE WHEN BOTH FINGERS ARE TOUCHING NOTHING
        public bool zero_fingertip_sensors { get; set; }
        //  the finger contact conditions that determine what our goal is
        //  Leaving this field blank will result in the robot closing until
        //  contact on BOTH fingers is achieved
        public sbyte contact_conditions { get; set; }
        //  predefined values for the above contact_conditions variable
        public const sbyte BOTH = 0; //  both fingers must make contact
        public const sbyte LEFT = 1; //  just the left finger 
        public const sbyte RIGHT = 2; //  just the right finger
        public const sbyte EITHER = 3; //  either finger, we don't care which

        public PR2GripperFindContactCommand()
        {
            this.zero_fingertip_sensors = false;
            this.contact_conditions = 0;
        }

        public PR2GripperFindContactCommand(bool zero_fingertip_sensors, sbyte contact_conditions)
        {
            this.zero_fingertip_sensors = zero_fingertip_sensors;
            this.contact_conditions = contact_conditions;
        }
    }
}
