/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Pr2GripperSensor
{
    public class PR2GripperGrabCommand : Message
    {
        public const string RosMessageName = "pr2_gripper_sensor_msgs/PR2GripperGrabCommand";

        //  The gain to use to evaluate how hard an object should be
        //  grasped after it is contacted. This is based on hardness
        //  estimation as outlined in TRO paper (see wiki).
        //  
        //  Try 0.03
        // 
        //  Units (N/(m/s^2))
        public double hardness_gain { get; set; }

        public PR2GripperGrabCommand()
        {
            this.hardness_gain = 0.0;
        }

        public PR2GripperGrabCommand(double hardness_gain)
        {
            this.hardness_gain = hardness_gain;
        }
    }
}
