/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Pr2GripperSensor
{
    public class PR2GripperForceServoData : Message
    {
        public const string RosMessageName = "pr2_gripper_sensor_msgs/PR2GripperForceServoData";

        //  Time the data was recorded at
        public Time stamp { get; set; }
        //  the force experienced by the finger Pads  (N)
        //  NOTE:this ignores data from the edges of the finger pressure
        public double left_fingertip_pad_force { get; set; }
        public double right_fingertip_pad_force { get; set; }
        //  the current gripper virtual parallel joint effort (in N)
        public double joint_effort { get; set; }
        //  true when the gripper is no longer moving
        //  and we have reached the desired force level
        public bool force_achieved { get; set; }
        //  the control state of our realtime controller
        public PR2GripperSensorRTState rtstate { get; set; }

        public PR2GripperForceServoData()
        {
            this.stamp = new Time();
            this.left_fingertip_pad_force = 0.0;
            this.right_fingertip_pad_force = 0.0;
            this.joint_effort = 0.0;
            this.force_achieved = false;
            this.rtstate = new PR2GripperSensorRTState();
        }

        public PR2GripperForceServoData(Time stamp, double left_fingertip_pad_force, double right_fingertip_pad_force, double joint_effort, bool force_achieved, PR2GripperSensorRTState rtstate)
        {
            this.stamp = stamp;
            this.left_fingertip_pad_force = left_fingertip_pad_force;
            this.right_fingertip_pad_force = right_fingertip_pad_force;
            this.joint_effort = joint_effort;
            this.force_achieved = force_achieved;
            this.rtstate = rtstate;
        }
    }
}
